version: 2
jobs:
  bottle-mojave:
    macos:
      xcode: "10.3.0"

    steps: &build-steps
      - add_ssh_keys
      - checkout

      - run:
          name: Install awscli
          command: >
            brew update; \
            brew install awscli

      - run:
          name: Build and run tests
          command: >
            bash -c .circleci/bottle-new-files.sh; \
            ls build/

  bottle-high-sierra:
    macos:
      xcode: "10.1.0"

    steps: *build-steps

  bottle-sierra:
    macos:
      xcode: "9.2.0"

    steps: *build-steps

workflows:
  version: 2
  build-bottles:
    jobs:
      - bottle-mojave:
          filters:
            branches:
              only: master
      - bottle-high-sierra:
          filters:
            branches:
              only: master
      - bottle-sierra:
          filters:
            branches:
              only: master
