version: 2
jobs:
  bottle-mojave:
    macos:
      xcode: "10.3.0"

    steps: &build-steps
      - add_ssh_keys
      - checkout
      - run:
          name: Build and run tests
          command: |
            bash -c .circleci/bottle-new-files.sh

  bottle-high-sierra:
    macos:
      xcode: "10.1.0"

    steps: *build-steps

  bottle-catalina:
    macos:
      xcode: "11.3.0"

    steps: *build-steps

workflows:
  version: 2
  build-bottles:
    jobs:
      - bottle-mojave:
          filters:
            branches:
              only: master
      - bottle-high-sierra:
          filters:
            branches:
              only: master
      - bottle-catalina:
          filters:
            branches:
              only: master
