name: Release Snowflake

on:
  workflow_dispatch:
    inputs:
      version_number:
       description: 'The version number to release'
       required: true
         
jobs:
  create-formula:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"
          
      - name: Find release type
        id: release_type
        env:
          IS_PRERELEASE: ${{ contains(github.event.inputs.version_number, 'rc') ||  contains(github.event.inputs.version_number, 'b') }}
        run: |
          echo ::set-output name=isPrerelease::$IS_PRERELEASE
          
      - name: Create file name
        id: naming_convention
        run: |
          if [ "$isPrerelease" == "true" ]
          then
            echo ::set-output name=fileName::echo 'dbt-snowflake@${{ github.event.inputs.version_number }}' | sed 's/\([[:digit:]]\)\.\([[:digit:]]\)\.\([[:digit:]]\)/\1.\2.\3-/g'
          else
            echo ::set-output name=fileName::dbt-snowflake@${{ github.event.inputs.version_number }}
          fi
          echo $fileName
          
      - name: Create PR branch
        run: |
          git checkout -b bumping-version/${{ github.event.inputs.version_number }}_$GITHUB_RUN_ID
          git push origin bumping-version/${{ github.event.inputs.version_number }}_$GITHUB_RUN_ID
          git branch --set-upstream-to=origin/bumping-version/${{ github.event.inputs.version_number }}_$GITHUB_RUN_ID bumping-version/${{ github.event.inputs.version_number }}_$GITHUB_RUN_ID

      - name: Create versioned formula file
        run: |
          python3 -m venv env
          source env/bin/activate
          pip install --upgrade pip
          pip install dbt-snowflake==${{ github.event.inputs.version_number }}
          pip install homebrew-pypi-poet
          poet -f dbt-snowflake > Formula/dbt-snowflake@${{ steps.naming_convention.outputs.fileName }}.rb
          sed -i 's/Shiny new formula/dbt-snowflake contains all of the code enabling dbt to work with Snowflake/g' Formula/dbt-snowflake@${{ steps.naming_convention.outputs.fileName }}.rb

      - name: Update latest release formula file
        if: ${{ steps.release_type.outputs.isPrerelease == 'false' }}
        run: |
          cp Formula/dbt-snowflake@${{ steps.naming_convention.outputs.fileName }}.rb Formula/dbt-snowflake.rb
          
      - name: Commit formula to branch
        uses: EndBug/add-and-commit@v7
        with:
          author_name: 'Github Build Bot'
          author_email: 'buildbot@fishtownanalytics.com'
          message: 'Creating snowflake formula file for version ${{ github.event.inputs.version_number }}'
          branch: 'bumping-version/${{ github.event.inputs.version_number }}_${{GITHUB.RUN_ID}}'
          push: 'origin origin/bumping-version/${{ github.event.inputs.version_number }}_${{GITHUB.RUN_ID}}'

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          author: 'Github Build Bot <buildbot@fishtownanalytics.com>'
          draft: true
          base: ${{github.ref}}
          title: 'Creating snowflake formula file for version ${{ github.event.inputs.version_number }}'
          branch: 'bumping-version/${{ github.event.inputs.version_number }}_${{GITHUB.RUN_ID}}'
