name: Release Snowflake

on:
  workflow_dispatch:
    inputs:
      version_number:
       description: 'The version number to bump to'
       required: true
      release_type:
       description: 'Type of release (i.e. final, rc1, b2)'
       required: true
       default: 'final'  
             
jobs:
  create-formula:
    runs-on: ubuntu-latest
    env:
      VERSION_NUMBER_COMPLETE: ${{ github.event.inputs.version_number }}${{ github.event.inputs.release_type }}
 
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"
          
      - name: Set formula file name suffix
        id: file_name
        env:
          FILE_NAME_SUFFIX: "${{ github.event.inputs.release_type == 'final' && github.event.inputs.version_number || github.event.client_payload.version_number-github.event.inputs.release_type }}"
        run: |
          echo ::set-output name=FILE_NAME_SUFFIX::$FILE_NAME_SUFFIX
          
      - name: Create PR branch
        run: |
          git checkout -b bumping-version/${{ env.VERSION_NUMBER_COMPLETE }}_$GITHUB_RUN_ID
          git push origin bumping-version/${{ env.VERSION_NUMBER_COMPLETE}}_$GITHUB_RUN_ID
          git branch --set-upstream-to=origin/bumping-version/${{ env.VERSION_NUMBER_COMPLETE }}_$GITHUB_RUN_ID bumping-version/${{ env.VERSION_NUMBER_COMPLETE }}_$GITHUB_RUN_ID

      - name: Create formula file for version
        run: |
          python3 -m venv env
          source env/bin/activate
          pip install --upgrade pip
          pip install dbt-snowflake==${{ env.VERSION_NUMBER_COMPLETE }}
          pip install homebrew-pypi-poet
          poet -f dbt-snowflake > Formula/dbt-snowflake@${{steps.variables.file_name.FILE_NAME_SUFFIX}}.rb
          sed -i 's/Shiny new formula/dbt-snowflake contains all of the code enabling dbt to work with Snowflake/g' Formula/dbt-snowflake@${{steps.variables.file_name.FILE_NAME_SUFFIX}}.rb

      - name: Create formula file for final version
        if: ${{ github.event.inputs.release_type == 'final' }}
        run: |
          cp Formula/dbt-snowflake@${{steps.variables.file_name.FILE_NAME_SUFFIX}}.rb Formula/dbt-snowflake.rb
          
      - name: Commit formula to branch
        uses: EndBug/add-and-commit@v7
        with:
          author_name: 'Github Build Bot'
          author_email: 'buildbot@fishtownanalytics.com'
          message: 'Creating snowflake formula file for version ${{env.VERSION_NUMBER_COMPLETE}}'
          branch: 'bumping-version/${{env.VERSION_NUMBER_COMPLETE}}_${{GITHUB.RUN_ID}}'
          push: 'origin origin/bumping-version/${{env.VERSION_NUMBER_COMPLETE}}_${{GITHUB.RUN_ID}}'

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          author: 'Github Build Bot <buildbot@fishtownanalytics.com>'
          draft: true
          base: ${{github.ref}}
          title: 'Creating snowflake formula file for version ${{env.VERSION_NUMBER_COMPLETE}}'
          branch: 'bumping-version/${{env.VERSION_NUMBER_COMPLETE}}_${{GITHUB.RUN_ID}}'
